### ISSUE TITLE
Binding waardelijst TE002.002 bestaat dubbel

### ISSUE THREAD

**Issue by helmavdl** [Nictiz/zib-transitie-richtlijnen-docs#1]
TE002.002 is incorrect. Dit zou TE001.002 moeten zijn

**Comment by GuidoOut** [comment]
Welke van de twee TE002.002 zou naar TE001.002 moeten worden aangepast?

**Comment by helmavdl** [comment]
Degene in Binding Waardelijst

**Comment by helmavdl** [comment]
Deze mag wat mij betreft wel dicht
